### PR TITLE
Fix new links in README.md

### PR DESCRIPTION
**Pull request by tonyfast**
Fixed the links to the new interact features in the readme.

### CODE REVIEW

**Comment by bollwyvl** [comment]
I build README from an ipynb, will get around to updating that soon with
these fixes.

**Comment by tonyfast** [comment]
That is kind of bad ass.  I just found that in the repo.

**Comment by bollwyvl** [comment]
Well, the idea is to generate rst for pypi and md for github... Though gh
supports rst, too so maybe i should just concentrate on that.. I does not
render on pypi for some reason, so i should get that ironed out.

**Comment by bollwyvl** [comment]
Decided to actually move the examples. Thanks again for pointing out the discrepancy.

**Pull request closed without merging**
